eval "$(starship init zsh)"

export ZSH="$HOME/.oh-my-zsh"

#ZSH_THEME="robbyrussell"


ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=246'

plugins=(git fzf-tab zsh-autosuggestions zsh-syntax-highlighting)

source $ZSH/oh-my-zsh.sh
setopt globdots


alias pa="php artisan"
alias pas="php artisan serve"
alias repairCommands="php artisan cache:clear && php artisan route:clear && php artisan optimize && php artisan view:clear"
alias gs="git status"
alias nrd="npm run dev"
alias gc="git commit -m"
alias gp="git push origin main"
alias gitAuth="git config --global credential.helper store"


alias c="clear"
alias ls="eza --icons --oneline --git-repos --git"
alias ll="eza --icons --git-repos --git --no-user --changed -l"
alias la="eza -a --icons --no-user -l"

alias routerWebServer='echo "https://192.168.0.1"'

# Herd injected PHP 8.4 configuration.
export HERD_PHP_84_INI_SCAN_DIR="/Users/mariusz/Library/Application Support/Herd/config/php/84/"


# Herd injected NVM configuration
export NVM_DIR="/Users/mariusz/Library/Application Support/Herd/config/nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm

[[ -f "/Applications/Herd.app/Contents/Resources/config/shell/zshrc.zsh" ]] && builtin source "/Applications/Herd.app/Contents/Resources/config/shell/zshrc.zsh"

# Herd injected PHP binary.
export PATH="/Users/mariusz/Library/Application Support/Herd/bin/":$PATH


# Herd injected PHP 8.5 configuration.
export HERD_PHP_85_INI_SCAN_DIR="/Users/mariusz/Library/Application Support/Herd/config/php/85/"

