# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="powerlevel10k/powerlevel10k"
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=246'
plugins=(git fzf-tab zsh-autosuggestions zsh-syntax-highlighting)
source $ZSH/oh-my-zsh.sh

# fzf-tab explicit source (after compinit)
source ~/.oh-my-zsh/custom/plugins/fzf-tab/fzf-tab.plugin.zsh
setopt globdots

# Aliases
#linux
alias p="sudo pacman"
alias clock="peaclock" 
alias c="clear"
alias ls="eza --icons --git-repos --git"
alias ll="eza --icons --git-repos --git --no-user --changed -l"
alias la="eza -a --icons --no-user -l"
alias pipieWireReset="systemctl --user restart pipewire pipewire-pulse wireplumber"
alias dbtoggle='sudo systemctl is-active --quiet mariadb && sudo systemctl stop mariadb || sudo systemctl start mariadb'
alias dbstatus='systemctl status mariadb'
alias help='bat Documents/obsidian-luna-pc/arch\ linux\ commands.md'
alias dot="cd ~/Documents/dotfiles/linux && ls"
alias conf="cd ~/.config && ls"

#coding
alias pa="php artisan"
alias pas="php artisan serve"
alias repairCommands="php artisan cache:clear && php artisan route:clear && php artisan optimize && php artisan view:clear"
alias nrd="npm run dev"
alias crd="composer run dev"



# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
export PATH="$HOME/.config/composer/vendor/bin:$PATH"
